backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false, hint: "1–2 sentences for previews" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/content/homepage/homepage.md"
        label: "Hero Section"
        name: "hero"
        fields:
          - { label: "Headline", name: "headline", widget: "string", required: false }
          - { label: "CTA Text", name: "cta", widget: "string", required: false }

  - name: "contact"
    label: "Contact Page"
    files:
      - file: "src/content/contact/contact.md"
        label: "Contact Info"
        name: "contact_content"
        fields:
          - { label: "Page Title", name: "title", widget: "string", required: false }
          - { label: "Intro Text", name: "intro", widget: "markdown", required: false }
          - { label: "Thank You Message", name: "thank_you", widget: "string", required: false }
